
name: build-dxc

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  info:
    runs-on: ubuntu-24.04
    outputs:
      COMMIT: ${{ steps.info.outputs.COMMIT }}
      BUILD_DATE: ${{ steps.info.outputs.BUILD_DATE }}
    steps:
      - name: Get Latest Commit Id
        id: info
        run: |
          echo COMMIT=`git ls-remote https://github.com/microsoft/DirectXShaderCompiler HEAD | awk '{ print $1 }'` >> ${GITHUB_OUTPUT}
          echo BUILD_DATE=`date +'%Y-%m-%d'` >> ${GITHUB_OUTPUT}

  build-win:
    runs-on: windows-2022
    needs: info
    strategy:
      matrix:
        arch: [x64, arm64]
    env:
      COMMIT: ${{ needs.info.outputs.COMMIT }}
      BUILD_DATE: ${{ needs.info.outputs.BUILD_DATE }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build Script
        id: build
        shell: bash
        run: bash build.sh win ${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dxc-win-${{ matrix.arch }}-${{ needs.info.outputs.BUILD_DATE }}
          path: dxc-win-${{ matrix.arch }}-${{ needs.info.outputs.BUILD_DATE }}.zip
          if-no-files-found: error
          compression-level: 0

  build-mac:
    runs-on: macos-latest
    needs: info
    strategy:
      matrix:
        arch: [arm64]
    env:
      COMMIT: ${{ needs.info.outputs.COMMIT }}
      BUILD_DATE: ${{ needs.info.outputs.BUILD_DATE }}
    steps:

      - name: Update XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build Script
        id: build
        shell: bash
        run: bash build.sh mac ${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dxc-mac-${{ matrix.arch }}-${{ needs.info.outputs.BUILD_DATE }}
          path: dxc-mac-${{ matrix.arch }}-${{ needs.info.outputs.BUILD_DATE }}.zip
          if-no-files-found: error
          compression-level: 0

  release:
    runs-on: ubuntu-24.04
    needs: [info, build-mac, build-win]
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:

      - name: Create GitHub Release
        run: |
          gh release create ${{ needs.info.outputs.BUILD_DATE }} -R "${GITHUB_REPOSITORY}" -t '${{ needs.info.outputs.BUILD_DATE }}'

      - name: Get Artifacts From Build Steps
        uses: actions/download-artifact@v4
        with:
          pattern: dxc-*-*-${{ needs.info.outputs.BUILD_DATE }}
          merge-multiple: true

      - name: Upload Artifacts to GitHub Release
        run: gh release upload '${{ needs.info.outputs.BUILD_DATE }}' dxc-*-*-${{ needs.info.outputs.BUILD_DATE }}.zip -R "${GITHUB_REPOSITORY}"
